# MARKET BASKET ANALYSIS

In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel("groceries.xlsx",header=None) #imported data

In [2]:
df.fillna(0,inplace=True) #preprocessing - - replacing Nan values with 'zero'
df

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,citrus fruit,semi-finished bread,margarine,ready soups,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,tropical fruit,yogurt,coffee,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,whole milk,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,pip fruit,yogurt,cream cheese,meat spreads,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,other vegetables,whole milk,condensed milk,long life bakery product,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,sausage,chicken,beef,hamburger meat,citrus fruit,grapes,root vegetables,whole milk,butter,whipped/sour cream,...,0,0,0,0,0,0,0,0,0,0
9831,cooking chocolate,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9832,chicken,citrus fruit,other vegetables,butter,yogurt,frozen dessert,domestic eggs,rolls/buns,rum,cling film/bags,...,0,0,0,0,0,0,0,0,0,0
9833,semi-finished bread,bottled water,soda,bottled beer,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9834,chicken,tropical fruit,other vegetables,vinegar,shopping bags,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
trans = []
for i in range(0,len(df)):
    trans.append([str(df.values[i,j]) for j in range(0,32) if str(df.values[i,j])!='0'])

In [4]:
from mlxtend.preprocessing import TransactionEncoder #imported trasactionencoder from mlxtend
encode = TransactionEncoder()
df = encode.fit_transform(trans)
df = pd.DataFrame(df, columns = encode.columns_)

In [5]:
df.columns

Index(['Instant food products', 'UHT-milk', 'abrasive cleaner',
       'artif. sweetener', 'baby cosmetics', 'baby food', 'bags',
       'baking powder', 'bathroom cleaner', 'beef',
       ...
       'turkey', 'vinegar', 'waffles', 'whipped/sour cream', 'whisky',
       'white bread', 'white wine', 'whole milk', 'yogurt', 'zwieback'],
      dtype='object', length=169)

In [6]:
df.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [7]:
from mlxtend.frequent_patterns import apriori
itemsets=apriori(df, min_support = 0.02, use_colnames = True)
itemsets           #support values for frequent itemsets

      support                                         itemsets
0    0.033452                                       (UHT-milk)
1    0.052466                                           (beef)
2    0.033249                                        (berries)
3    0.026029                                      (beverages)
4    0.080529                                   (bottled beer)
..        ...                                              ...
117  0.032232                 (whipped/sour cream, whole milk)
118  0.020742                     (whipped/sour cream, yogurt)
119  0.056024                             (yogurt, whole milk)
120  0.023183  (other vegetables, root vegetables, whole milk)
121  0.022267           (other vegetables, yogurt, whole milk)

[122 rows x 2 columns]

- TOP 10 ITEMSETS:

In [8]:
frequent_itemsets=itemsets.sort_values(by=['support'], ascending=False) #sorting to get top 10 frequent itemsets
Top_ten=frequent_itemsets[:10]
Top_ten

     support            itemsets
57  0.255516        (whole milk)
39  0.193493  (other vegetables)
43  0.183935        (rolls/buns)
49  0.174377              (soda)
58  0.139502            (yogurt)
5   0.110524     (bottled water)
44  0.108998   (root vegetables)
53  0.104931    (tropical fruit)
47  0.098526     (shopping bags)
46  0.093950           (sausage)

In [9]:
from mlxtend.frequent_patterns import association_rules
rules_mlxtend = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules_mlxtend.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(other vegetables),(whole milk),0.193493,0.255516,0.074835,0.386758,1.513634,0.025394,1.214013
1,(whole milk),(other vegetables),0.255516,0.193493,0.074835,0.292877,1.513634,0.025394,1.140548
2,(rolls/buns),(whole milk),0.183935,0.255516,0.056634,0.307905,1.205032,0.009636,1.075696
3,(whole milk),(rolls/buns),0.255516,0.183935,0.056634,0.221647,1.205032,0.009636,1.048452
4,(yogurt),(whole milk),0.139502,0.255516,0.056024,0.401603,1.571735,0.020379,1.244132

In [10]:
#rules=rules_mlxtend[(rules_mlxtend['lift'] >= 1)]

- Top 10 Rules based on Lift

In [11]:
Top_rules=rules_mlxtend.sort_values(by=['lift'], ascending=False) #sorting to get top 10 rules based on lift
Top_rules[:10]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
84,(root vegetables),"(other vegetables, whole milk)",0.108998,0.074835,0.023183,0.212687,2.842082,0.015026,1.175091
81,"(other vegetables, whole milk)",(root vegetables),0.074835,0.108998,0.023183,0.309783,2.842082,0.015026,1.290900
122,(tropical fruit),(pip fruit),0.104931,0.075648,0.020437,0.194767,2.574648,0.012499,1.147931
123,(pip fruit),(tropical fruit),0.075648,0.104931,0.020437,0.270161,2.574648,0.012499,1.226392
83,(other vegetables),"(root vegetables, whole milk)",0.193493,0.048907,0.023183,0.119811,2.449770,0.013719,1.080555
82,"(root vegetables, whole milk)",(other vegetables),0.048907,0.193493,0.023183,0.474012,2.449770,0.013719,1.533320
8,(other vegetables),(root vegetables),0.193493,0.108998,0.047382,0.244877,2.246605,0.026291,1.179941
9,(root vegetables),(other vegetables),0.108998,0.193493,0.047382,0.434701,2.246605,0.026291,1.426693
91,"(other vegetables, whole milk)",(yogurt),0.074835,0.139502,0.022267,0.297554,2.132979,0.011828,1.225003
94,(yogurt),"(other vegetables, whole milk)",0.139502,0.074835,0.022267,0.159621,2.132979,0.011828,1.100890

 - Check for frozensets

In [16]:
#Top_rules[Top_rules['antecedents'] == frozenset(['whole milk'])]
#Top_rules[Top_rules['antecedents'] == frozenset(['other vegetables'])]
#Top_rules[Top_rules['antecedents'] == frozenset(['root vegetables'])]
#Top_rules[Top_rules['antecedents'] == frozenset(['(pip fruit'])]
#Top_rules[Top_rules['antecedents'] == frozenset(['tropical fruit'])]
#Top_rules[Top_rules['antecedents'] == frozenset(['yogurt'])]